name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: mahamimran20
          outputs: dist/github-contribution-grid-snake.svg
          # 🎨 Color customization
          color_snake: "#4fc3f7"          # Snake color (GitHub green)
          color_dots: "#0d1117,#0a2342,#144272,#205295,#2c74b3" 
          # order: empty, low, mid, high, max activity
          color_bg: "#0d1117"   # << This forces a dark background

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

